version: '3.1' 

services:
  webvowl-docker:
    container_name: webvowl-docker
    image: openkbs/webvowl-docker
    build:
      context: .
      dockerfile: Dockerfile
    command: catalina.sh run
    #env_file:
    #  - ./.env
    volumes:
      ## -- Use $HOME/data
      #- $HOME/data-docker/knime-vnc-docker/data:/home/developer/data 
      #- $HOME/data-docker/knime-vnc-docker/workspace:/home/developer/workspace 
      ## -- Use current directory as root for mapping Volumes: --
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace
    ## -------------------------------
    ## -- Change to your specific port
    ## -------------------------------
    ports:
      - "18088:8080"
    ## -----------------------------
    ## -- Network setup if needed --
    ## -----------------------------
    # networks:
    #  - dev_network

#networks:
#  dev_network:
#    external:
#      name: dev_network


